Repository precice-forschungsprojekt/precice-generator, pull requests merged in 2024-12, with the labels that each got.

#8 Create README.md
  README.md
Labels: documentation

#32 Fix everything gets added into profiling
  controller_utils/precice_struct/PS_PreCICEConfig.py
Labels: bug, Task

#39 Implemented clean.sh script generation
  FileGenerator.py
  templates/template_clean.sh
Labels: Task
